# -*- coding: utf-8 -*-
"""Copy of 21 Days B3 Day 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lIvCP70Ln0yLx3hq-VStJbYAwiviV-e8

# Project 2: In-Depth Exploratory Data Analysis (EDA)
## Netflix Content Analysis 🎬

**Project Objective:** To perform an in-depth exploratory data analysis of the Netflix dataset. We will explore trends in content production, identify popular genres, analyze content ratings, and understand the distribution of movies and TV shows on the platform. This project builds on foundational EDA by introducing time-series analysis and more complex data cleaning and transformation techniques.

### Core Concepts We'll Cover:
1.  **Data Cleaning & Transformation:** Handling missing values and converting data types (especially dates).
2.  **Time-Series Analysis:** Analyzing how content has been added to Netflix over the years.
3.  **Text Data Manipulation:** Parsing and analyzing columns with multiple values, like `listed_in` (genres) and `cast`.
4.  **Geographical & Rating Analysis:** Understanding where content comes from and its maturity level.
5.  **Feature Engineering:** Creating new, insightful features like 'content age'.
6.  **Advanced Visualization:** Creating insightful plots to understand distributions and relationships in the data.

### Step 1: Setup - Importing Libraries

As always, we begin by importing our essential data science toolset, including a new library for word clouds.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

sns.set_style('darkgrid')

"""### Step 2: Data Loading and Initial Inspection

We'll load the `netflix_titles.csv` dataset and perform a high-level overview.
"""

!git clone 'https://github.com/HarshvardhanSingh-13/Datasets'

df = pd.read_csv('/content/Datasets/Netflix_Titles Dataset/netflix_titles.csv')
df.head()

df.tail()

df.info()

"""**Interpretation of `.info()`:**
- We have 7787 entries (titles).
- **Key Problem:** The `date_added` column is of type `object` (a string), not a `datetime` object. We cannot perform time-based analysis until this is corrected.
- **Missing Values:** `director`, `cast`, `country`, `date_added`, and `rating` all have missing values. `director` has the most significant number of nulls.
"""

df.describe()

"""### Step 3: Data Cleaning and Transformation

This step is critical for ensuring our analysis is accurate. We will handle missing values and correct data types.

#### **Theoretical Concept: Data Type Conversion & Handling Nulls**
Data often comes in non-ideal formats. Storing dates as strings, for example, prevents us from extracting components like the year or month, or from plotting data over time. Converting columns to their proper data types (`pd.to_datetime`, `.astype()`) is a fundamental preprocessing step.

For null values, we have several strategies:
1.  **Drop:** If only a very small percentage of rows have missing data, dropping them might be acceptable (`.dropna()`).
2.  **Fill/Impute:** Replace missing values with a placeholder (like "Unknown") or a statistical measure (like the mode for categorical data). This is useful when you don't want to lose the other information in those rows.
"""

df.isnull().sum()

## 1) Handling missing values in 'Director' and 'cast'

df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')

df.isnull().sum()

## 2) Handling missing values in 'country'
mode_country = df['country'].mode()[0]
df['country'] = df['country'].fillna(mode_country)

df.isnull().sum()

# 3. Drop the few rows with missing 'date_added' and 'rating'
# Since the number is small (less than 0.2% of data), dropping them is a safe option.

df.dropna(subset=['date_added','rating'], inplace=True)

df.isnull().sum()

## 4) Convert 'date_added' to a datetime format
df['date_added'] = pd.to_datetime(df['date_added'], format='mixed', dayfirst=False)

df.head()

df.info()

## 5) Creating a new feature for year and month

df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

df.head()

"""### Step 4: Exploratory Data Analysis & Visualization

#### 4.1 What is the distribution of content type?
"""

df['type'].value_counts()

plt.figure(figsize=(8,6))
type_counts = df['type'].value_counts()
plt.pie(type_counts, labels=type_counts.index, autopct='%1.1f%%', startangle=140, colors=['#e60023', '#221f1f'])
plt.title('Proportion of Movies vs. TV Shows')
plt.show()

"""**Insight:** The Netflix library is dominated by Movies, which make up roughly 70% of the content in this dataset.

#### 4.2 How has content been added over time?
"""

content_over_time = df.groupby(['year_added', 'type']).size().unstack().fillna(0)

plt.figure(figsize=(14,8))
content_over_time.plot(kind = 'line', marker = 'o', figsize=(14,8))
plt.title('Content Added to Netflix Over the Years (by Type)')
plt.xlabel('Year Added')
plt.ylabel('Number of Titles Added')
plt.legend(title='Content Type')
plt.grid(True)
plt.show()

"""**Insight:** By separating movies and TV shows, we can see that while both grew significantly, the addition of movies accelerated much more dramatically, peaking in 2019. The growth in TV shows has been more steady. There appears to be a slight slowdown in content additions in 2020 and 2021, which could be due to the COVID-19 pandemic affecting productions or the dataset being incomplete for the latest year.

#### 4.3 What are the most popular genres?

#### **Theoretical Concept: Handling Multi-Value Text Columns**
The `listed_in` column contains strings with multiple genres separated by commas (e.g., "Dramas, International Movies"). To analyze each genre individually, we need to transform the data. A common technique is to:
1.  **Split** the string in each row into a list of genres.
2.  **Explode** the DataFrame so that each genre in the list gets its own row, duplicating the other information for that title.
This allows us to perform a `value_counts()` on the genres.
"""

genres = df.assign(genre = df['listed_in'].str.split(', ')).explode('genre')

# Get the top 15 genres and their counts
top_genres_counts = genres['genre'].value_counts().reset_index()
top_genres_counts.columns = ['genre', 'count'] # Rename columns for clarity

# Select only the top 15 for plotting
top_genres_counts_plot = top_genres_counts.head(15)

plt.figure(figsize=(12, 8))
sns.barplot(y='genre', x='count', data=top_genres_counts_plot, palette='mako', hue='genre', legend=False)
plt.title('Top 15 Genres on Netflix')
plt.xlabel('Count')
plt.ylabel('Genre')
plt.show()

"""**Insight:** "International Movies" is the most common genre tag, highlighting Netflix's global content strategy. This is followed by Dramas, Comedies, and Action & Adventure.

#### 4.4 What is the distribution of content duration?
"""

## Seperate movies and TV Shows

movies_df = df[df['type'] == 'Movie'].copy()
tv_shows_df = df[df['type'] == 'TV Show'].copy()

tv_shows_df['duration'] = tv_shows_df['duration'].str.replace(' Seasons','').str.replace(' Season','').astype(int)

movies_df['duration'] = movies_df['duration'].str.replace(' min','').astype(int)

# Plot the distributions
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# Movie Duration Distribution
sns.histplot(ax=axes[0], data=movies_df, x='duration', bins=50, kde=True, color='skyblue').set_title('Movie Duration Distribution (minutes)')

# TV Show Season Distribution
sns.countplot(ax=axes[1], x='duration', data=tv_shows_df, palette='rocket', order=tv_shows_df['duration'].value_counts().index, hue='duration', legend=False).set_title('TV Show Season Distribution')

plt.show()

"""**Insight:**
- The majority of movies on Netflix are between 80 and 120 minutes long, which is standard for feature films.
- The vast majority of TV shows on Netflix are short-lived, with most having only 1 season. This could reflect a strategy of producing many pilots and only renewing the most successful ones, or a focus on limited series.

#### 4.5 Where does the content come from? (Geographical Analysis)
"""

## Handle the mult-country listed
countries = df.assign(country = df['country'].str.split(', ')).explode('country')

# Get the top 15 countries and their counts
top_countries_counts = countries['country'].value_counts().reset_index()
top_countries_counts.columns = ['country', 'count'] # Rename columns for clarity

# Select only the top 15 for plotting
top_countries_counts_plot = top_countries_counts.head(15)

plt.figure(figsize=(12, 10))
sns.barplot(y='country', x='count', data=top_countries_counts_plot, palette='viridis', hue='country', legend=False)
plt.title('Top 15 Content Producing Countries on Netflix')
plt.xlabel('Number of Titles')
plt.ylabel('Country')
plt.show()

"""**Insight:** The United States is by far the largest producer of content available on Netflix. However, India is a very strong second, which explains why so many of the top actors were from India. The UK, Japan, and South Korea also represent major content markets for the platform, emphasizing its global nature.

#### 4.6 What are the maturity ratings of the content?
"""

plt.figure(figsize=(12,8))
sns.countplot(x='rating', data=df, order=df['rating'].value_counts().index, palette='crest', hue='rating', legend=False)
plt.title('Distribution of Content Ratings on Netflix')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""**Insight:** A large portion of Netflix's content is aimed at mature audiences, with `TV-MA` (Mature Audience) and `TV-14` (Parents Strongly Cautioned) being the two most common ratings. This suggests a focus on adult viewers over content for children (`TV-G`, `TV-Y`).

### Step 5: Feature Engineering - Content Freshness
Let's create a new feature to analyze how old content is when it gets added to Netflix. This can tell us about their acquisition strategy (buying old classics vs. releasing new originals).
"""

## Creating a column 'age_on_netflix' feature

df['age_on_netflix'] = df['year_added'] - df['release_year']

## Filter out any potential errors when added_year is before release_year

content_age = df[df['age_on_netflix'] >= 0]

plt.figure(figsize=(14, 7))
sns.histplot(data=content_age, x='age_on_netflix', bins=50, kde=True)
plt.title('Distribution of Content Age When Added to Netflix')
plt.xlabel('Content Age (Years)')
plt.ylabel('Number of Titles')
plt.show()

"""**Insight:** The large spike at `0` indicates that a significant amount of content is added in the same year it's released, which is characteristic of "Netflix Originals." However, there is a very long tail, showing that Netflix also heavily invests in acquiring licensed content that can be decades old, building a deep library of classic films and shows.

### Step 6: Deeper Multivariate Analysis
"""

# Analyze movie duration across different top genres
top_genres = genres['genre'].value_counts().index[:5]
genres_movies = genres[(genres['type'] == 'Movie') & (genres['genre'].isin(top_genres))].copy()
genres_movies['duration_min'] = genres_movies['duration'].str.replace(' min', '').astype(int)

plt.figure(figsize=(15, 8))
sns.boxplot(data=genres_movies, x='genre', y='duration_min', palette='pastel', hue='genre', legend=False)
plt.title('Movie Duration by Top Genres')
plt.xlabel('Genre')
plt.ylabel('Duration (minutes)')
plt.xticks(rotation=45)
plt.show()

"""**Insight:** While the median duration for most top genres is similar (around 90-100 minutes), we can see some interesting variations. For example, Dramas tend to have a wider range of durations, with many longer films. International Movies also show a broad distribution, reflecting diverse filmmaking styles from around the world.

### Step 7: Word Cloud from Content Descriptions
As a final visual analysis, let's generate a word cloud from the `description` column to see what themes and words are most common in Netflix content.
"""

text = ' '.join(df['description'])

## Generating the visual
wordcloud = WordCloud(width=800, height=400, background_color='black').generate(text)

# Display the generated image
plt.figure(figsize=(15, 10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Most Common Words in Netflix Content Descriptions', fontsize=20)
plt.show()

"""**Insight:** The word cloud highlights common themes and subjects. Words like "life," "family," "love," "young," "friends," and "world" are prominent, suggesting that much of the content revolves around human relationships and personal journeys. Action-oriented words like "find," "secret," and "new" also appear frequently.

### Step 8: Final Conclusion and Summary of Insights

This in-depth EDA of the Netflix dataset has revealed several key characteristics and strategies of the platform's content library.

**Key Findings:**
1. **Content Strategy:** Netflix's library is movie-heavy (~70%), and the platform aggressively added content between 2016-2019. Their strategy involves a mix of brand new originals (added the same year they are released) and a deep library of licensed older content.
2. **Global Dominance:** While the US is the top content producer, the platform is heavily international, with India being a massive contributor. This is reflected in the top genres ("International Movies") and most frequent actors.
3. **Target Audience:** The content library is skewed towards mature audiences, with `TV-MA` and `TV-14` being the most common ratings.
4. **Content Format & Genre:** Dramas and Comedies are universally popular genres. Most movies stick to a standard 90-120 minute runtime, while the vast majority of TV shows only last for a single season, suggesting a high-risk, high-reward approach to series production.
5. **Common Themes:** Descriptions of content frequently revolve around universal themes of life, family, love, and discovery.

**Limitations:** This dataset is a snapshot in time and lacks viewership data. Therefore, our analysis is of the *supply* of content, not its *demand* or popularity. Nonetheless, this EDA provides a strong, multi-faceted understanding of the composition and evolution of the Netflix library.

# Submission Q's

* How has the distribution of content ratings changed over time?
* Is there a relationship between content age and its type (Movie vs. TV Show)?
* Can we identify any trends in content production based on the release year vs. the year added to Netflix?
* What are the most common word pairs or phrases in content descriptions?
* Who are the top directors on Netflix?

**Q1.How has the distribution of content ratings changed over time?**
"""

rating_over_time = df.groupby(['year_added', 'rating']).size().reset_index(name='count')
rating_over_time_pivot = rating_over_time.pivot(index='year_added', columns='rating', values='count').fillna(0)
plt.figure(figsize=(14, 8))
rating_over_time_pivot.plot(kind='bar', stacked=True, figsize=(14, 8))
plt.title('Distribution of Content Ratings Over Time')
plt.xlabel('Year Added to Netflix')
plt.ylabel('Count')
plt.legend(title='Rating')
plt.show()

"""**Conclusion**
Over time, the distribution of content ratings on Netflix has shifted heavily toward mature ratings. Starting around 2016, there is a sharp rise in TV-MA and TV-14 titles, driven by the growth of Netflix Originals. Family and kid-oriented ratings remain relatively flat. This suggests that Netflix has progressively focused more on adult and mature-themed content over the last decade.

**Q2.Is there a relationship between content age and its type (Movie vs. TV Show)?**
"""

plt.figure(figsize=(12,6))
sns.boxplot(data=content_age, x='type', y='age_on_netflix', palette='Set2')
plt.title("Content Age When Added to Netflix: Movies vs TV Shows")
plt.xlabel("Content Type")
plt.ylabel("Age on Netflix (Years)")
plt.show()

"""**Conclusion**
TV Shows tend to be newer (more recent releases), while Movies include a larger amount of older content, showing a strong relationship between content type and content age.

**Q3. Can we identify any trends in content production based on the release year vs. the year added to Netflix?**
"""

pivot_years = df.pivot_table(values='show_id',index='year_added', columns='release_year', aggfunc='count', fill_value=0)
plt.figure(figsize=(15, 8))
sns.heatmap(pivot_years, cmap='viridis')
plt.title('Content Production Trends Over Time')
plt.xlabel('Release Year')
plt.ylabel('Year Added to Netflix')
plt.show()

age_trend = df.groupby('year_added')['age_on_netflix'].mean()
plt.figure(figsize=(12,6))
age_trend.plot(marker='o')
plt.title("Average Content Age Added to Netflix Each Year")
plt.xlabel("Year Added")
plt.ylabel("Average Age (Years)")
plt.grid(True)
plt.show()

"""**Conclusion**

Yes, there are clear trends in content production based on the release year vs. year added to Netflix.
In the early years, Netflix primarily added older licensed movies and shows, resulting in a large gap between release year and added year.
Starting around 2016, the gap narrows significantly, indicating a shift towards adding newly produced content, largely due to the rapid expansion of Netflix Originals.
Most content added in recent years is very new (age close to 0), showing that Netflix now focuses heavily on producing and releasing original content the same year it is created.
While older movies are still occasionally added, the dominant trend is a clear move toward new, fresh content being added to the platform.

**Q4.What are the most common word pairs or phrases in content descriptions?**
"""

import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize
import string

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))

from nltk.util import ngrams
from collections import Counter

# Combine all descriptions into one string
text = ' '.join(df['description']).lower()

# Tokenize
tokens = word_tokenize(text)

# Remove stopwords + punctuation
tokens = [word for word in tokens if word not in stop_words and word not in string.punctuation]

# Bigrams (2-word phrases)
bigrams = list(ngrams(tokens, 2))

# Trigrams (3-word phrases)
trigrams = list(ngrams(tokens, 3))

# Count most common
bigram_counts = Counter(bigrams).most_common(20)
trigram_counts = Counter(trigrams).most_common(20)

bigram_counts, trigram_counts

bigram_df = pd.DataFrame(bigram_counts, columns=["bigram", "count"])
bigram_df['bigram'] = bigram_df['bigram'].apply(lambda x: ' '.join(x)) # Convert tuples to strings
plt.figure(figsize=(12,6))
sns.barplot(data=bigram_df, x="count", y="bigram", palette="viridis", hue='bigram', legend=False)
plt.title("Top 20 Most Common Bigrams in Descriptions")
plt.show()

"""**Conclusion**
By analyzing bigrams and trigrams from the description field, we find that Netflix content commonly uses phrases related to relationships (“falls in love,” “best friend”), youth-oriented stories (“high school student,” “young woman”), and mission-driven narratives (“must find,” “sets out”).
This indicates that Netflix’s content heavily focuses on personal relationships, emotional journeys, and character-driven storytelling.

**Q5.Who are the top directors on Netflix?**
"""

top_directors = df['director'].value_counts().head(10)
plt.figure(figsize=(12,6))
sns.barplot(x=top_directors.values, y=top_directors.index, palette="crest", hue=top_directors.index, legend=False)
plt.title("Top 10 Directors on Netflix")
plt.xlabel("Number of Titles")
plt.ylabel("Director")
plt.show()

"""**Conclusion**
The most prolific directors on Netflix tend to be those who have created stand-up comedy specials (e.g., Raúl Campos, Jan Suter, Jay Karas) because Netflix hosts many comedy shows they directed.
"""